### ISSUE TITLE
Primary navigation should use larger font or fill more of the screen width

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#100]
At some point the main top menu (About, News, Guidelines & Standards, etc.) stopped being aligned left with the main body text.  The font size also looks relatively small compared to the body text heading.

On the call 7/31 Randal said he thinks that happened when he worked out how to make the default page width wider, and that he had some idea how to fix.

**Comment by RSD-accessboard** [comment]
Yes, do we want to make the header wider on all pages, or make some of the other pages narrower if they are not standards with the columns? I'm leaning towards the latter because some of your ages in the about us are pretty sparse and don't look good when their that widescreen

**Comment by RSD-accessboard** [comment]
Reduced width of regular pages and posts to align with header menu width
