### ISSUE TITLE
Architectural barriers act guides

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#103]

**Comment by RSD-accessboard** [comment]
Randall to upload better version of ABA guides

**Comment by kengdoj** [comment]
@RSD-accessboard - let me know if the master files for the aba guides are ready for me to start working on them. Thanks!

**Comment by RSD-accessboard** [comment]
I did not get to them, all I was going to do was copy  from our website and paste them here:

https://euangoddard.github.io/clipboard2markdown/

 to see if I could get a cleaner version.   could you try giving it a shot?  make sure you also get the chapter 6 architectural barriers act guides, I don't think they are in the repository yet.
