### ISSUE TITLE
netlify bugs and failed to build

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#119]
Still having issues creating a news post through netlify. Says does not save, can't change status, can't publish. But it does show up as a branch upon saving. Also Federalist build failed

**Comment by apburnes** [comment]
Looks like a misconfiguration in the NetlifyCMS media settings.  Updated and pushed to the branch https://github.com/atbcb/usab-uswds/commit/f7156cad7939aac1fc0e2967f7ff6333fa14358a
