### ISSUE TITLE
Heading links anchors copy link feature

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#120]
Like to add a feature like this:

https://developers.google.com/web/fundamentals/design-and-ux/responsive/images

Where each heading gets a copy link anchor

Found this plug-in on GitHub, but it doesn't have copy feature only create a link feature
https://github.com/craftcms/anchors#plugin-api

**Comment by RSD-accessboard** [comment]
feature added, need to clean up CSS

**Comment by RSD-accessboard** [comment]
see # example for css
https://caniuse.com/css-line-clamp

**Comment by bruce-usab** [comment]
Am I correct to be reading this to be for the auto-cutoff feature we discussed Friday?

If so --  nice find -- but <q>proprietary and undocumented</q> makes me think we should just live without.
