### ISSUE TITLE
finish chapter 10 migration guides

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#136]
I was hoping I could do all of the chapter 10 guides, but now must move on to preparing for my webinar. I was not able to finish chapter 10-play-areas. This is the only one that I did not finish. I got the first one third done,  and the last section, but this guide is extremely extremely long with lots of side-by-side pictures which were very annoying. I created an include to help.  If you finish the architectural barriers act guides and have some free time can you take on this one? I will not be doing website migration stuff until I have my webinar prepared.

**Comment by kengdoj** [comment]
ok, I'll work on it. Is your latest in the master?

**Comment by RSD-accessboard** [comment]
yes

**Comment by kengdoj** [comment]
Done.
