### ISSUE TITLE
Center all images and style all tables

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#138]
I tried creating a class and applying that to the div in the_layouts/standards.html file, and then giving that class default image styling of margin auto, or margin left margin right auto, etc. but I could not get it to automatically center the images in all the standard documents. Then the CSS broke. I'll leave it up to what you to figure out how to get all of our figures centered in the standards documents like ADA, and PROWAG, PVAG, etc.

Since everything started breaking at the end, I did not pull that branch into master. You guys can start from scratch on this issue

**Comment by kengdoj** [comment]
Changing priority to enhanced navigation version

**Comment by kengdoj** [comment]
Tables fixed in PR #235

**Comment by kengdoj** [comment]
Prowag figures done.

**Comment by kengdoj** [comment]
@RSD-accessboard - I'm fixing figures in ABA standards. ABA's ch3 and ch5 copy ADA's chapters. Are you keeping the ADA chapters?

**Comment by kengdoj** [comment]
Ok then I will fix the images in the ADA where the ABA duplicates them.

**Comment by kengdoj** [comment]
ABA standards figures done.

**Comment by bruce-usab** [comment]
Formatting tables seems like it will take quite a while.  I think we should close this issue and open a new one for each document that needs work.  Or maybe a new issue with milestones?  (But I must confess, I do not know how the milestone mechanic works.)

**Comment by RSD-accessboard** [comment]
This issue can be closed, Kathy did a lot of work on this
