### ISSUE TITLE
Go live!

### ISSUE THREAD

**Issue by apburnes** [atbcb/usab-uswds#139]
Go live with the website
=================

## How to

The site review process requires:
1) filling out this quick [form](https://docs.google.com/forms/d/1ujDu9mUNmHuCG2Mx5JYFUaXthYrf304yMpBrGOEudMA/edit)
2) webscan of your site
3) source code scan of your repository
4) your DNS admin to set 2 CNAMEs for your domain (1 is an acme certificate challenge to obtain your ssl certificate)
5) Federalist team to create a CloudFront distribution to serve your site

The security scans can be executed relatively quickly. The web scan typically takes 2-5 days but I can submit an expedited request for a quicker turnaround (1~2 days).  The source code scan can be turned around in a day. Once your site development is completed, please notify federalist-support@gsa.gov and I can submit your site for scan.  Typically, the scans come back clean, but if there are any Medium, High or Critical vulnerabilities reported they will have to be remediated and re-scanned before we proceed.

Once the scans are completed successfully, your DNS admin will need to set 2 CNames which will enable us to create the Cloudfront Distribution we require to serve your site at your domain.  Once your domain's DNS is set and Cloudfront distribution is created, your site will be accessible at your custom domain.

The biggest time variables are the site scans and setting your DNS.

The details of our launch process can be found in our [launch checklist](https://federalist.18f.gov/documentation/launch-checklist/) documentation.

**Comment by bruce-usab** [comment]
I am checking in with Charles Washington on one question on the form and the CNames.

**Comment by bruce-usab** [comment]
Confirmed (9/8) with DNS provider that CNAMES values set last week were not quite correct.
