### ISSUE TITLE
91 and UFAS

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#142]
Add the 1991 standards, add links to both 91 standards and UFA's. UFA is already added just there is no link to it

**Comment by bruce-usab** [comment]
I have not looked for it yet.  Is UFAS formatted as a collection?

**Comment by RSD-accessboard** [comment]
No, it’s a single page, use html version . I think its /ufas

**Comment by RSD-accessboard** [comment]
this content is on the site under _pages/guidelines and standards boat we don't link to it. The plan is to link to it from the timeline that Dave will get us

**Comment by bruce-usab** [comment]
Per call 9/9, still needs 508 cleanup.

**Comment by PresleyAB** [comment]
Add page.title to 1991 ADAAG. Also create side navagation.
