### ISSUE TITLE
site statistics

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#143]
Any built in features?

**Comment by apburnes** [comment]
The Digital Analytics Program (DAP) is a free service.  You will need to send them an email to dap@support.digitalgov.gov and then you can fill out your request https://docs.google.com/forms/d/1BVcvBge74kaWpSkIaQ1x1sfAE3aa0YMnVe3kXuD8z9k/viewform.  You will then update the site config with your DAP info [here](https://github.com/atbcb/usab-uswds/blob/d7c259cba270fc3e7334e48d20a08b50b301e962/_config.yml#L38).

**Comment by apburnes** [comment]
Here's the Federalist docs on the program https://federalist.18f.gov/documentation/customer-responsibilities/#you-own-any-custom-code-on-your-webpage

**Comment by bruce-usab** [comment]
We are signed up with DAP now, and I have copied over the GA code to the Federalist site.  But is there more to it than that?
