### ISSUE TITLE
Add to and from for webinar times on news posts

### ISSUE THREAD

**Issue by apburnes** [atbcb/usab-uswds#146]
Currently, the `webinar-date` field is available for editors to create a date timestamp from when the webinar will start.  Editors need a way to specify how long a webinar lasts.

**Comment by apburnes** [comment]
@RSD-accessboard what do you think about these two options?
- Changing the `webinar-date` timestamp field to `webinar-start` and `webinar-end` timestamp fields.
- Keep the `webinar-date` timestamp field and add a `duration` integer field for minutes.

**Comment by RSD-accessboard** [comment]
Start time and end time, option number one

Randall Duchesneau III
US Access Board
1331 F Street NW, Suite 1000 ▪ Washington DC, 20004
(202) 272-0044
duchesneau@access-board.gov<mailto:duchesneau@access-board.gov>

Disclaimer: Technical assistance provided in this email is intended solely as informal guidance; it is neither a determination of your legal rights or responsibilities, nor a statement of the official views of the U.S. Access Board or any other federal agency.  Any links to non-federal websites are provided as a courtesy and do not represent an endorsement of the linked information, products, or services.

**Comment by RSD-accessboard** [comment]
I'm realizing that the display of webinars is counterintuitive. I should create a section called upcoming webinars and have Jekyll display posts with a webinar start date greater than today, and another section 4 past webinars with start date less than today. Currently it's just putting them in order of start date, but that puts webinar scheduled 2 months out advanced higher than the upcoming webinar for this week etc. Is there a way we can get Jekyll to do this? I think so, but I also think it would depend on whenever it's rebuilt unless we use JavaScript.

Your thoughts Andrew before I take a stab at it?

**Comment by bruce-usab** [comment]
i can't think of another work around.

The site will get rebuilt every time we add a webinar or blog post, so that should be at least once every couple weeks, even during slow months.  If someone notices that an "up coming" happened a few days ago, I do not think that is a big deal.

**Comment by RSD-accessboard** [comment]
When using netlify to add a post, the "webinar" Boolean is required, should default to false instead of null. also webinar start time should be null instead of defaulting to now. I will try to address these, keeping notes here
