### ISSUE TITLE
Social links on blog

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#165]
Social links on blog are not correct.  _Config.yml has the correct values, but this is not propagated to new and webinar pages.

**Comment by RSD-accessboard** [comment]
Added Twitter and YouTube social link. How do you update social link icons? Where is all that code coming from? I couldn't get the YouTube icon to appear

**Comment by bruce-usab** [comment]
Thanks @RSD-accessboard 

The GitHub icon is hard-coded SVG, which is an interesting choice.  I am not sure about the YouTube one.

**Comment by RSD-accessboard** [comment]
will revisit this once we have our font  awesome account.
