### ISSUE TITLE
Fix homepage USAB logo when in mobile

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#169]
the star should either resize to a smaller image or fix the overflow when screen is reduced to mobile version

**Comment by bruce-usab** [comment]
Also we need new logo and seal that matches USDWS theme colors.  I think the navy blue we are using is x162E51.  @RSD-accessboard have you come across a a dark red in our theme?

**Comment by bruce-usab** [comment]
Just noting that this is still an issue after switch to SVG version of logo. See email 9/14 from Brian Bard.

**Comment by bruce-usab** [comment]
Except for the En Espanol bit, contrast is good.
