### ISSUE TITLE
404 error page not found - 

### ISSUE THREAD

**Issue by tc-usab** [atbcb/usab-uswds#172]
https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/site/atbcb/usab-uswds/about/contact.html

link to email directory for FOIA page leads to a 404 error. 

404 / Page not found
You might want to double-check your link and try again, or return to the homepage.

This is a default 404 page for Federalist, a hosting service for federal websites.

**Comment by bruce-usab** [comment]
Closed by https://github.com/atbcb/usab-uswds/pull/178
