### ISSUE TITLE
Page not found - link to external site.  Error appears in both live website and Work in progress website

### ISSUE THREAD

**Issue by tc-usab** [atbcb/usab-uswds#181]
Access Board page:  No FEAR Act Notice 

Dead link appears in 2nd paragraph under Whistleblower Protection Laws, beginning :"Retaliation against an employee or applicant for making a protected disclosure is prohibited by 5 U.S.C. § 2302(b)(8). If you believe that you have been the victim of whistleblower retaliation, you may file a written complaint (Form OSC-11) with the U.S. Office of Special Counsel. Complaints may be filed online using OSC’s e-filing system (online form), or, alternatively, forms may be downloaded from **OSC’s website (fillable form)**, completed offline, and submitted to OSC by mail or facsimile. Please see Form OSC-11 for additional..."

OSC’s website (fillable form)
https://osc.gov/Pages/PageNotFoundError.aspx?requestUrl=https://osc.gov/Resources/osc11.pdf

Page not found 
​The page you're looking for doesn't exist.​​
 
Check for a typo in the URL, or go to the site home

**Comment by bruce-usab** [comment]
Thanks Tim!

Please find the correct link, then edit the file.  Call me (via Teams) so I can walk you through the process.

File to edited can be found by following this path:
View repo -> _pages --> no-fear-notice.md

**Comment by bruce-usab** [comment]
Tim and Bruce discovered (8/27) that OSC has taken down the PDF form.

Post launch, @bruce-usab should ask Gretchen how she wants to change page.
