### ISSUE TITLE
Enhanced nav Data tables

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#182]
True data tables in all of our standards, need to be formatted correctly in HTML and utilize class usa-table.

The priority ADA version is going to be the enhanced navigation version which is found in_pages/guidelines-standards/enhanced-ADA.html

**Comment by kengdoj** [comment]
This has been addressed by adding a script to the enhanced-ADA.html file (PR #191). 

Do you want to link a new .js or manually copy the script for the ABA standards files?

**Comment by RSD-accessboard** [comment]
I’d like to see if we could refer to the script in the layout, then it would apply to all standards pages.

**Comment by kengdoj** [comment]
Do you want to ask Andrew about that?

**Comment by bruce-usab** [comment]
I should also mention that the data class on the current site has a little bit more functionality than usa-table.

For example, see the zebra striping here:
https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-regulatory-impact-analysis#_Toc471376905

**Comment by kengdoj** [comment]
usa-tables class added via script. will open a new issue for the alternate row shading from bruce.
