### ISSUE TITLE
Images inside tables

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#183]
All of the standards need to be checked to see if they are incorrectly using tables to style images with figure text above or below.

Potential temporary solution, add role=presentation, or remove table and properly center and style image with figure text below or above

**Comment by bruce-usab** [comment]
I very much agree that we should not be using tables as a way to format images.  My preferred syntax would be FIGURE and FIGCAPTION but those will take some experimentation to test with USWDS.
https://www.w3schools.com/tags/tag_figcaption.asp

**Comment by kengdoj** [comment]
https://designsystem.digital.gov/figure/ is what I found for figure. @bruce-usab I don't think this is what you want

**Comment by RSD-accessboard** [comment]
They just did a using div and img I do like some of the styling out appears on the card, but You want to use figure HTML?


1

2

3

4

5

6

7

<div class="usa-image-block">

  <img src="/assets/img/typography_example_apple_pie.png"  alt="Apple Pie">

  <div class="usa-image-text-block">

    <h2 class="usa-display">Apple pie</h2>

    <p class="usa-image-text">It's delicious.</p>

  </div>

</div>

**Comment by bruce-usab** [comment]
I do **_not_** think we should use figure/figcaption for highlight.html and other places (like with this example) where the images and text are mostly just presentational.

**Comment by kengdoj** [comment]
enhanced ADA and ABA, Prowag standards figures done.

**Comment by kengdoj** [comment]
I don't think transportation vehicles needs this done.

**Comment by bruce-usab** [comment]
There are also a lot of images where the figure caption is graphical text.  But I am not in any hurry to fix those, since really the better solution is replace bitmaps with SVG.

**Comment by RSD-accessboard** [comment]
And we need to utilize the liquid asset feature for better caching. This is pretty important for the single page ADA and ABA with a lot of images. I think this is taking longer For the page to load because this

**Comment by kengdoj** [comment]
pvag done.
