### ISSUE TITLE
Accordions

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#184]
Use accordions on standard landing pages that have a lot of text on the about page. Also on the prescription drugs page and anywhere else relevant. Use USWDS style accordions

**Comment by bruce-usab** [comment]
As far as I can tell, the USWDS accordions still do not an expand all feature.  But I imagine you can lift code from the KMS.

**Comment by RSD-accessboard** [comment]
The 18 F people did give us a link to an example of a site they helped build that had an expand all feature, I can’t seem to find the link though

**Comment by kengdoj** [comment]
Do you want the toc accordion or the content itself to accordion?

**Comment by bruce-usab** [comment]
My first priority would be for accordion as warranted for content.  I would suggest our Privacy page (with the SORNs) as an excellent initial candidate.

Current [issue USWDS issue](https://github.com/uswds/uswds/issues/3654) links to original issue (which has some good examples) and their current prototype.

**Comment by RSD-accessboard** [comment]
It would be nice if we could figure out how to separate the accordion JavaScript features from the according CSS styling. Currently I use the USWDS accordion and have to undo all of their styling. Let me know if you come across something that just has accordion feature without any styling

**Comment by kengdoj** [comment]
USWDS is working on in its application

[testing link](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-accordion-all/components/preview/layout--content.html)

**Comment by bruce-usab** [comment]
That implementation seems pretty good to me!  I was not expecting much more than they are already demonstrating.

**Comment by kengdoj** [comment]
PVAG pages are taking very long for me to fix. I won't have time to do this before launch.

**Comment by kengdoj** [comment]
waiting for USWDS solution.
