### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#185]
Do we need to add other stuff on the front page like about the technical assistance line? Upcoming webinars, latest news? Or are we keeping a very simplified

**Comment by yanchulis** [comment]
We are keeping the homepage simple and don’t need to add news items, webinars, etc.

Dave

Dave Yanchulis
Director, Office of Technical and Information Services
U.S. Access Board
(202) 272-0026 (v), (202) 272-0027 (TTY)
yanchulis@access-board.gov<mailto:yanchulis@access-board.gov>
www.access-board.gov<http://www.access-board.gov>
