### ISSUE TITLE
 cleanup chapter 10 outdoor ABA guide

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#187]
I added the guide content, images, and  PDF file. Links and image styling and headings all need to be cleaned up. Also you might want to copy the tables again in HTML and clean those up in HTML directly, instead of the markdown versions

The guides can be found here:

https://www.access-board.gov/guidelines-and-standards/recreation-facilities/outdoor-developed-areas/a-summary-of-accessibility-standards-for-federal-outdoor-developed-areas

This may be something you can assign to Sarah, at least for headings etc.

**Comment by RSD-accessboard** [comment]
I don't expect you to get to this today, so it's still in the branch am working on. I'll pull it into master by the end of the day

**Comment by kengdoj** [comment]
On the [Trails page](https://www.access-board.gov/guidelines-and-standards/recreation-facilities/outdoor-developed-areas/a-summary-of-accessibility-standards-for-federal-outdoor-developed-areas/trails), this is a broken link - 

The State University of New York conducted the “Anthropometry of Wheeled Mobility Project.” The final report for this project is available at www.udeworld .com/documents/anthropometry/pdfs/AnthropometryofWheeledMobility Project_FinalReport.pdf.

**Comment by bruce-usab** [comment]
For that link, please use:
http://idea.ap.buffalo.edu/wp-content/uploads/sites/110/2020/01/AnthropometryofWheeledMobilityProject_FinalReport.pdf

**Comment by kengdoj** [comment]
Thanks, @bruce-usab .

Displaying that long link on the page runs over into the right border so I modified the page text like this:

> The [final report for "Anthropometry of Wheeled Mobility Project"](http://idea.ap.buffalo.edu/wp-content/uploads/sites/110/2020/01/AnthropometryofWheeledMobilityProject_FinalReport.pdf) recommends that, [...]

**Comment by bruce-usab** [comment]
Thanks, good call!

**Comment by RSD-accessboard** [comment]
Should consider hosting PDF file ourselves in option. Might be, I believe we funded the research

**Comment by bruce-usab** [comment]
Yes, see acknowledgements.  I suspect it not a well formed PDF.
