### ISSUE TITLE
H4, H5 and H6 CSS styling

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#192]
To make the standards that utilize multiple heading levels readable, everything beyond H4 should be at least as large as the body text, and we could remove the margin below the heading. For example see 407.2.3.1

**Comment by bruce-usab** [comment]
I very much agree that H4/H5/H6 should be at body text size.

I am okay if H4/H5/H6 are visually indistinguishable.  I am also okay if the formatting for H4/H5/H6 ends up being pretty subtle (like maybe normal font weight, and only italics for the visual distinction).

With the 508 provisions, Kathy found one place where we really could have used an H7.  I expect that ADAAG/ABAAS goes that deep as well.

**Comment by kengdoj** [comment]
I have tried to modify the h5 and h6 font sizes in uswds-theme-typography.scss, but it isn't working to make them bigger.

```
$theme-h4-font-size: "sm";
$theme-h5-font-size: "sm";
$theme-h6-font-size: "sm";
```

Nothing else I've tried works. I'm out of ideas...

**Comment by RSD-accessboard** [comment]
That would’ve been my first guess too, When you change the CSS file you need to cancel the Build and do a new bundle exec jekyll serve

**Comment by RSD-accessboard** [comment]
I made the same changes and enabled the stylesheet in the index.CSS, it's showing up in the inspector but it's being overridden by each 5 from  div.standards

I'll give it another go next week otherwise low priority and will just ask Andrew

**Comment by bruce-usab** [comment]
In the .scss file, you can try adding !important to your class

**Comment by bruce-usab** [comment]
Andrew showed us how to fix this on the call 9/2.  Pulled into master with PR yesterday.
