### ISSUE TITLE
Readme.md best practices

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#212]
Bruce would like most directories to include a readme.md file as a way to document what is going where.

@RSD-accessboard has some concern that this is clutter, and will generate files that exposed in the sitemap.

What are some best practices for this?

At Randal's suggestion, but tried adding front matter with output: false but that was worse -- since the readme.md file then appeared in the ToC sidebar menu.

**Comment by RSD-accessboard** [comment]
Close this or you want to revisit adding readme?

**Comment by bruce-usab** [comment]
Agreed that their is no compelling reason to keep this open.
