### ISSUE TITLE
Reconsider use of H1 versus H2 in Standards and Guidelines

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#214]
H2 are page titles.  H3 are the primary entries that display in the sidebar menus.  H4/H5/H6 nest semantically under H3.  This is all good!

How much are we using H1?  The Devis/Joomla site underused H1, and (in hindsight) that was a mistake because one H1 per page is ideal, and some of standards need H7.

OTOH, sparing use of H1 elsewhere means that it is available for single-file versions of standards and guidelines.

**Comment by RSD-accessboard** [comment]
H1 is Chapter, H2 is section (example 404 doors). I don't think we can go up any further
