### ISSUE TITLE
Standards and Guidelines pages present as directories rather than files

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#215]
It is not crucial, since everything is working, but in general, files (on the back-end) should present as files (on the public-facing front end).  For example:

It would be just a little bit better if [.../mde/chapter-m2/
](https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/site/atbcb/usab-uswds/mde/chapter-m2/
) was something like .../mde/ch2.html

It is very nice how our about.md pages render as indexes for their associated directories, so I would not want to mess that up!

**Comment by RSD-accessboard** [comment]
the URL in that case is rendering based on/: path/

If we change the file names in the collection it will change the URL. What is the consistent format you want to use? 
ch-
chapter-
Ch-
…

**Comment by bruce-usab** [comment]
Public facing URLs for the ADAAS (using the advanced navigation) are good.  So does this issue go away as the advanced navigation is applied to other collections?

The filenames in the collections should be shorter, so ch2 or m2 instead of chapter-m2.   As you note, that is an easy fix.

The URL coming from the /:path/ and the filename being rendered as a path (instead of a file) seems like a trickier issue!

**Comment by bruce-usab** [comment]
Just a note:  Nine pages pages in Spanish have a URL ending in .html
See:
...[.../es/](https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/site/atbcb/usab-uswds/es/l)

**Comment by RSD-accessboard** [comment]
could explore trying " /:path" instead of  "/:path/"

This might get you to/ADA/guides/CH2
 I don't really like having to add ".html" all the time. Our current site does not require you to add ".html"

**Comment by bruce-usab** [comment]
Joomla site really did let pages end in a char.

Jekyll pages ending in a slash are really ending in /index.html
