### ISSUE TITLE
MDE cleanup

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#216]
I noticed a couple of bugs with the MDE standards:
- [x] About follows Preamble (it should be first)
- [x] Page titled "Text of the Standards" is not actually that.  I think it is the last part of the Preamble.  And it resolves to an odd URL.

**Comment by bruce-usab** [comment]
Reopening, sorry.  I want to do something different with the "Text of the Standards" bit.

I think it should go after the preamble (before Chapter 1) and be renamed <q>Appendix to Part 1195</q> or <q>Table of Contents</q>

**Comment by RSD-accessboard** [comment]
It’s fixed, I just haven’t pushed my changes yet.
