### ISSUE TITLE
Banner for Standards and Guidelines does not sufficiently mobile responsive

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#219]
From @kengdoj email 8/27.

Example:

![image](https://user-images.githubusercontent.com/24896889/91462839-a3bc1580-e858-11ea-83ae-0b1af56b7c0f.png)

**Comment by RSD-accessboard** [comment]
yes, I may note note of this in another issue
#169

**Comment by bruce-usab** [comment]
Yes, I let Kathy know that we had an issue already for the star logo.  I am hoping that fixing that helps with the text overlap.  The titles and headers seem to me like a bigger (lol) usability issue.

**Comment by bruce-usab** [comment]
Just noting that this is still an issue after switch to SVG version of logo.

**Comment by bruce-usab** [comment]
Closing this issue to track in https://github.com/atbcb/usab-uswds/issues/169
