### ISSUE TITLE
 ADA/ABA guide links to the standards don't work

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#224]
create a regular expression to link to the standards page directly to the section. Should be straightforward with the enhanced ADA version, a bit more challenging with architectural barriers act version because they on separate pages

Kathy are you comfortable with regular expressions? Or should I take on this

**Comment by kengdoj** [comment]
Better for you to handled this @RSD-accessboard. I don't know how to do this.

**Comment by bruce-usab** [comment]
This will be nice, but I think it can wait until post launch.  We have six business days.

**Comment by RSD-accessboard** [comment]
I made some good progress with the ADA guides, but then it turns out there’s a bunch of links that don’t use the consistent formatting. I might take another stab at it or we will just have some links that work and some don’t.

Here are my notes on the regular expressions I had to create in case anyone wants to learn Hint hint


[ADA Standards](../ada-standards.html)
[ADA Standards]({{ site.baseurl }}/ada/)



To change bold to heading level in markdown
search:
\*\*(.*)\*\*\\
Or
\*\*(.*)\*\*
(*remember to use regular expression and make sure match new line is not checked)

replace:
#### \1
### $1
*Visual Studio code uses $'s instead of \'s


to find the  3 digit section links used in the ADA guides
\[\[§([0-9][0-9][0-9])\]\((.*)\)\]
and replace with new website link
[[§$1]({{ site.baseurl }}/ada/#ada-$1)]

To find the XXX.X section links used in the ADA guides
\[\[§([0-9][0-9][0-9]).([0-9])\]\((.*)\)\]
and replace with new website link
[[§$1.$2]({{ site.baseurl }}/ada/#ada-$1_$2)]

To find the next XXX.XX section links like 404.10
\[\[§([0-9][0-9][0-9]).([0-9][0-9])\]\((.*)\)\]
And replace with the new website link
[[§$1.$2]({{ site.baseurl }}/ada/#ada-$1_$2)]


To find the  XXX.X.X section links
\[\[§([0-9][0-9][0-9]).([0-9]).([0-9])\]\((.*)\)\]

and replace with
[[§$1.$2.$3]({{ site.baseurl }}/ada/#ada-$1_$2_$3)]




ABA
to find the  3 digit section links used in the ABA guides
\[\[§F([0-9][0-9][0-9])\]\((.*)\)\]

**Comment by bruce-usab** [comment]
Thanks for posting the regular expressions!

**Comment by kengdoj** [comment]
ugh i guess i'll learn how to do this :-/. I'll start with the aba guides...

**Comment by kengdoj** [comment]
where is the UFAS file located? it is linked from the aba ch 1 guide

**Comment by RSD-accessboard** [comment]
{{ site.baseurl }}/ufas/

_Pages/guidelines-standards/ufas.html

Randall Duchesneau III
US Access Board
1331 F Street NW, Suite 1000 ▪ Washington DC, 20004
(202) 272-0044
duchesneau@access-board.gov<mailto:duchesneau@access-board.gov>

Disclaimer: Technical assistance provided in this email is intended solely as informal guidance; it is neither a determination of your legal rights or responsibilities, nor a statement of the official views of the U.S. Access Board or any other federal agency.  Any links to non-federal websites are provided as a courtesy and do not represent an endorsement of the linked information, products, or services.

**Comment by kengdoj** [comment]
Links in the ABA guides should be good.
