### ISSUE TITLE
Edit to Board history 

### ISSUE THREAD

**Issue by tc-usab** [atbcb/usab-uswds#227]
https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/site/atbcb/usab-uswds/about/history.html 

By passing the ABA, Congress intended the federal government to set as an example for state and local governments and for private industry. 

Edit by dropping the word "as"  --  "...to set an example...."

**Comment by bruce-usab** [comment]
Tim, you have your permissions cleared up, so please:

- open the file in the GitHub repository
- click edit
- make your change
- follow the prompts for making a new branch
- You are done!  Pleas resist the urge to send an email!

Creating the branch will send me a notification.

**Comment by tc-usab** [comment]
Trying to find the GitHub repository for this issue.  I went to https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/site/atbcb/usab-uswds/about/ but that doesn't allow editing.  I'm looking for the repo file.

**Comment by bruce-usab** [comment]
Closed by https://github.com/atbcb/usab-uswds/pull/244
