### ISSUE TITLE
ICT class=h7

### ISSUE THREAD

**Issue by kengdoj** [atbcb/usab-uswds#236]
Edit class="h7" to have a role of heading level 7:

`<span class="h7">407.8.3.2.1 Operable Part Height for ICT with Obstructed Forward Reach</span>` 

should be 

`<div role="heading" aria-level="7">407.8.3.2.1 Operable Part Height for ICT with Obstructed Forward Reach</div>`

Want me to do a PR?

**Comment by bruce-usab** [comment]
Thanks!  Please do a PR.  I appreciated (1) your catching this, and (2) educating me how to mark it up  in the future.

**Comment by kengdoj** [comment]
Will do. I should've done it this way in the 508 KMS so it wouldn't need to be fixed here!
