### ISSUE TITLE
Add CSS for data tables - alternate row shading

### ISSUE THREAD

**Issue by kengdoj** [atbcb/usab-uswds#240]
For example, see the zebra striping here:
https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-regulatory-impact-analysis#_Toc471376905

**Comment by bruce-usab** [comment]
If I remember right, I wrote two classes.  One for odd rows having a shading, and the other for even rows having the shading.

**Comment by kengdoj** [comment]
Shading added.
