### ISSUE TITLE
Delete duplicate entry on page -Rulemaking History

### ISSUE THREAD

**Issue by tc-usab** [atbcb/usab-uswds#250]
September 6, 1991 – ADA Accessibility Guidelines (ADAAG) for Transportation Facilities
September 6, 1991 – ADA Accessibility Guidelines (ADAAG) for Transportation Vehicles

https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/site/atbcb/usab-uswds/about/rulemaking.html

**Comment by tc-usab** [comment]
Double checked this entry.  The original listing is correct.  NO change needed.  Close issue.

**Comment by bruce-usab** [comment]
>  @tc-usab closed this 3 days ago
Nice job managing the issue tracker!
