### ISSUE TITLE
Standards layout sort by order number

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#251]
make this an if statement, so if order-number is null the build can still go through

**Comment by bruce-usab** [comment]
This could help resolve a questions I was having:

What is a good directory to use for files that that are related to a collection, but not part of the collection per se?

In particular. I am thinking there were will be files from the ICT timeline that I need put someplace.  I might use \_pages for now, or I could make a sub-folder under \_ict.

**Comment by RSD-accessboard** [comment]
Use_pages

For example_pages/advisory-committee-reports/Passenger-vessels/
Or

_Pages/guidelines-standards/ICT/

**Comment by bruce-usab** [comment]
Thanks!

**Comment by RSD-accessboard** [comment]
now that I created the universal layout we can put similar pages within the collection and give them a different "TOC-group" so they can have a different style side navigation. I've completed this for the ADA and ABA. Still need to do the others, but it's a separate issue then this topic so closing this issue
