### ISSUE TITLE
Rail advisory committee report

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#252]
cleanup text of headings, and fix hyperlinks table of contents at the top. Possibly explore creating a side navigation panel by creating a new template. Post-launch

_pages/advisory-committee-reports/rail/final-report.md

**Comment by RSD-accessboard** [comment]
_pages/advisory-committee-reports/rail/final-report.md

**Comment by RSD-accessboard** [comment]
created a new layout called report

**Comment by bruce-usab** [comment]
Not that we need to figure this out now, but I am not a fan of deeply nested folders.  I think people tend to browse by category, so .../rail/advisory-committee-reports/final-report.md might be more intuitive than .../advisory-committed-reports/rail/final-report.md

I am not a fan of folders with hundreds of files, but also I am not a fan of folders with just three or four files!

For now, I will have Tim put ICT docs that we are pulling down into `\_pages\ict'

**Comment by RSD-accessboard** [comment]
Happy to revisit this once we scraped as much content as we can, but for the example you just gave the URL you suggest would have to be something like

ADA/vehicles/update-rail/advisory-committee/final-report

I wanted someone to propose a folder structure a while ago, Would’ve made it a lot easier, we have so many deeply nested documents that the more I scrape the more I find ones that don’t fit. Wait till you start looking into the research folder

**Comment by bruce-usab** [comment]
The directory structure you have got going makes sense for now.  Like you wrote, what you have works well for organizing documents as they are pulled in.  The directory names are self-explanatory, so that is very good.

Human friendly permalinks are the goal.  So I would expect the above file to present as something like:
> .../ada/rvaac/final-report.html

**Comment by RSD-accessboard** [comment]
No need to scrape image file s and rename links
