### ISSUE TITLE
Improve navigation from standards pages to their guides

### ISSUE THREAD

**Issue by kengdoj** [atbcb/usab-uswds#268]
I found having to go to the About page of the standards to get to the guides and then navigating to the guide I wanted to be less than ideal (especially when working on the guide links to the standards). 

Maybe add a link on each chapter page to its related guide (on the right side nav?).

**Comment by bruce-usab** [comment]
Seems like a good suggestion.  It does feel to me like the guides are too easy to miss still.
I certainly agree this is a Post Launch issue.

**Comment by bruce-usab** [comment]
May relate to issue https://github.com/atbcb/usab-uswds/issues/445

**Comment by RSD-accessboard** [comment]
this is fixed in the universal layout
