### ISSUE TITLE
ADA vehicle guides

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#28]
Add ADA vehicle guides content to the folder: **_ada-vehicles-guides**

current location: https://www.access-board.gov/guidelines-and-standards/transportation/vehicles/technical-assistance-manuals-on-adaag-for-transportation-vehicles/subpart-h-automated-guideway-transit-systems

- copy the content, paste it on this website to convert to markdown: https://euangoddard.github.io/clipboard2markdown/
- copy the converted markdown
- create a file in the ADA vehicle guides folder. Filename example: "subpart-h-guide.md"
- paste the converted markdown into the file
- the extraneous content at the top about printing and emailing
- add front matter:

```
---
title: 
order-number:
---
```

**Comment by bstinnette** [comment]
Testing
