### ISSUE TITLE
Animations video transcript  not loading

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#31]
captions file load under CC, but the video transcript box does not show any content

**Comment by bruce-usab** [comment]
Do we have a working example of another site that I can compare our code against?

Also, I need to get/create .vtt files for Signs and Sales Counters.

**Comment by RSD-accessboard** [comment]
I was Comparing it to the Oz Player website example

**Comment by bruce-usab** [comment]
.vtt files for Signs and Counters have been uploaded.

We should discuss on 8/6 if we want to use Oz or DOI player.

**Comment by RSD-accessboard** [comment]
I removed the video transcript box since it is not loading transcripts correctly. I tried to turn off captions by default because the captions are covering up the text in the videos, but I could not figure out how to turn off captions by default. Might want to inquire with Oz how to do this if we are sticking with this player.

**Comment by bruce-usab** [comment]
Is it all the videos which are having problems?  I did not notice it the last time I played one.

**Comment by kengdoj** [comment]
Is a transcript MVP if the captions are working?

**Comment by RSD-accessboard** [comment]
We are now using the Department of Interior version so closing out this issue
