### ISSUE TITLE
Create landing page for AI work

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#3214]
Currently USAB is using [blog article](https://www.access-board.gov/news/2024/07/09/u-s-access-board-holds-hearings-on-artificial-intelligence-ai-for-disability-community-and-ai-practitioners/) as an AI landing page and index.
- [x] Create content for landing page @dhokeefe and @amylnieves 
- [x] Decide where markdown page should live @bruce-usab and @dhokeefe 
- [ ] Put link to AI landing page into horizontal navigation page @bruce-usab

**Comment by bruce-usab** [comment]
This issue has dependency on #3215

**Comment by dhokeefe** [comment]
Draft landing page as of 8/2: https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.sites.pages.cloud.gov/preview/atbcb/usab-uswds/dhokeefe-ai/ai/

**Comment by bruce-usab** [comment]
I don't think we necessarily need AI as it's own menu item.  We can discuss 8/12.

**Comment by bruce-usab** [comment]
Last item in OP now OBE.
