### ISSUE TITLE
Site map links do not work on Federalist build

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#344]
Some issue with {{ site.baseurl }} going on in the link generation of the site map
https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/site/atbcb/usab-uswds/sitemap/

For example 1st link should go to
/ABA/
but instead goes to
https://access-board.gov/site/atbcb/usab-uswds/aba/

**Comment by apburnes** [comment]
Once the site goes live, you will update the site settings in Federalist and add the domain URL to the live site settings.  Then you kick off a build of the production branch and the site baseurl value will be `access-board.gov` and not `federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/site/atbcb/usab-uswds/`. Does that make sense?

**Comment by bruce-usab** [comment]
Sort of.  But I am not troubled by this not working without a domain name.  Could this be a similar issue to why our customized 404  is not displaying?
