### ISSUE TITLE
Board Members pages some work

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#347]

**Comment by bruce-usab** [comment]
Board Members pages is okay, but it uses in-line CSS for `figure `which is not a good coding practice.  Figures have `id` so moving that formatting to the .scss should be pretty straightforward.

Page uses liquid to generate most content from a data file, but it should have a sort filter added.  (Data file is alphabetical, so it works, but that is not a good way to do things.)

Also, it is a .md page, but it is mostly html (with liquid) and the content comes from a data file, so not so easy to maintain.

**Comment by RSD-accessboard** [comment]
Board members photos perspective warped, need to correct

**Comment by bruce-usab** [comment]
closed by #441
