### ISSUE TITLE
Add Spanish pages

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#36]
Devis site has nine pages in Spanish.

- We should add that content to website sooner than later, but can be after MVP.
- It might be useful to capture those nine pages from Joomla as opposed to archive.
- link can be from footer

**Comment by RSD-accessboard** [comment]
Remove the entire USA-secondary links class and you'll be left with a blue hyperlink. Alternatively we could overwrite the color by changing it from gray to black and maybe bolding it. Complicated way would be to change the class properties in USWDS CSS not worth it for one link

**Comment by RSD-accessboard** [comment]
Should be sure to copy the Spanish page contents so we don't lose that in the migration

**Comment by bruce-usab** [comment]
Spanish pages are up.  I will ask Mario to test.  We will need to revisit links.  And I have not tried to change the Secondary Nav color.

**Comment by RSD-accessboard** [comment]
Color is probably fine, since we haven’t styled the footer either. When we do style that we can make them consistent

**Comment by RSD-accessboard** [comment]
We can close out this issue right?

**Comment by bruce-usab** [comment]
Yes, color choices can be another issue.
