### ISSUE TITLE
504 contacts page

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#361]
Please check that links at top of page go to the right place:  Page is at:
[&hellip;/_pages/enforcement-504contacts.md](https://github.com/atbcb/usab-uswds/blob/master/_pages/enforcement-504contacts.md)

**Comment by RSD-accessboard** [comment]
this has been replaced with the fiber for contacts page generated with a collection and input through netlify. File is located in 
_contacts-504\
index.html

To do:

- [ ]  convert contact information into a visual table
- [ ]  make entire entry an accordion
- [ ]  improve styling and visual effects

Link location: /504-contacts/

**Comment by bruce-usab** [comment]
Very nice.  Permalink working as desired:  https://beta.access-board.gov/504-contacts/

Link from Enforcement page page works, but we probably will want to link this up elsewhere.

**Comment by bruce-usab** [comment]
Lines w/o content should probably not show at all.
I am seeing a bunch of spurious external link icons.

**Comment by RSD-accessboard** [comment]
That can be solved by making all of them if statements

**Comment by kengdoj** [comment]
Dan Sutherland hasn't been DHS's CRCL head in a looooong time. Has this data been checked for accuracy?

**Comment by RSD-accessboard** [comment]
This information was supposedly updated by Paul before he left

**Comment by bruce-usab** [comment]
We probably need direction from @yanchulis and maybe OGC as to who has lead for this data.  I think enforcement owns, and @RSD-accessboard has made it easy for someone maintain it.

I think it needs a date for last updated, and a notes field that is not part of the generated paged.

**Comment by yanchulis** [comment]
I previously recommended to Mario that we pare down this list for updating.  He agreed and followed up with a new & shorter list of contacts with some updated info.  I will send it to you both.

**Comment by RSD-accessboard** [comment]
It would be great if we could get Mario to input information. It should be user-friendly

**Comment by bruce-usab** [comment]
- Tabular presentation, two columns:  field /  value (unlabeled)
- Data in rows, use { if } and { end-if } to suppress fields with no values
- Could be accordions latter, so no need for index
- Each agency an accordion, then a data table for fields and value

s
