### ISSUE TITLE
Convert 504 Contacts page to data file

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#363]
Page is at:
[&hellip;/_pages/enforcement-504contacts.md](https://github.com/atbcb/usab-uswds/blob/master/_pages/enforcement-504contacts.md)

It really should be \_data

**Comment by bruce-usab** [comment]
@RSD-accessboard is working this to use Netlify UI from old Paul B. spreadsheet.  See PRs #392 and #392

**Comment by RSD-accessboard** [comment]
This is not completely finished, But can be a new issue. I created the netlify, but we still need to add all the content and verify the Index page rendering
