### ISSUE TITLE
Develop Netlify interface to 504 Contacts _data file

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#364]
Page scraped from Devis Joomla site is:
Page is at:
[&hellip;/_pages/enforcement-504contacts.md](https://github.com/atbcb/usab-uswds/blob/master/_pages/enforcement-504contacts.md)

- [ ] It really should be \_data file
- [ ] It really should be a \_data file with a Netlify interface -- so that OGC staff could maintain easily.

Q:  Can Netlify be used for maintenance, or is Netlify strictly for uploading?

**Comment by RSD-accessboard** [comment]
We can created as a collection and use the front matter to store the data, similar to how _tags &_authors works. Then you can edit them in netlify
