### ISSUE TITLE
Crop Board Members images

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#367]
Several Board Members photos (in circular cut-out) look odd, almost certainly because they are all rectangular photos.

This task is to crop each one into a square.  Dimensions TBD, but 240x is good round number with many divisors.

**Comment by RSD-accessboard** [comment]
We mentioned this in #347

**Comment by bruce-usab** [comment]
Yes, that is what prompted me to make an issue _just_ for the portrait photos.
