### ISSUE TITLE
Need Skip Nav functionality for left sidebar menus

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#377]
WCAG SC 2.4.1 Bypass Blocks:
> A mechanism is available to bypass blocks of content that are repeated on multiple Web pages. (Level A)

USWDS gets us a very nice Skip Nav, but that only bypasses the main navigation.  We need a means to skip through the left sidebar menus as well.

**Comment by bruce-usab** [comment]
Awesome, thanks!

**Comment by kengdoj** [comment]
Still need to do the About page...

**Comment by RSD-accessboard** [comment]
I’d like to get a better understanding of the changes you have to make so we can make them across the site and cut down on the number of layouts we have. I also need to consolidate some of the layouts that I created. It may also be a good time to revisit the about pages side navigation, and loop them into a consistent side navigation theme. With a single layout

**Comment by bruce-usab** [comment]
Consolidating layouts would be good.  @kengdoj, after the site goes live, the plan is for us to still have a beta.access-board.gov.  I think harmonizing the menus can wait until then.  I think the next couple of weeks should focus on capturing more obscure articles from the Joomla/Devis site.

**Comment by kengdoj** [comment]
My attempts so far to add the skip to TOC link on the about page have resulted in adding a vertical scroll bar, so that there are 2 scroll bars on the page. If you don't plan to revamp the side nav for the about page until after mvp, I'll continue to try to fix this.

**Comment by bruce-usab** [comment]
FWIW, I think we passed MVP deadline a few weeks back.  Yes, there are still some open MVP issues.

As far as I am concerned, the About sidenav is okay for go live for WWW launch.

I would like a skip nav for the About menu, but I since I think we may be revisiting the whole functionality of the About menu, it doesn't make sense to spend too much effort on it.

**Comment by RSD-accessboard** [comment]
Kathy just added that in

**Comment by bruce-usab** [comment]
Nice!

I read @kengdoj comment to say she was giving up for a bit!

2nd skip nav is working great on About pages!

**Comment by bruce-usab** [comment]
Closing this issue because I understand the extra skip nav on standards pages is subsumed with consolidating layouts.
