### ISSUE TITLE
Add ICT collection

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#38]
Convert Revised 508 Standards (including pictures and 255) to HTML suitable for Jekyll collection, following @RSD-accessboard pattern for other collections.

- Four (4) pages with Appendices as H1
- H2: Chapter titles are H2
- H3:  Major headings (i.e, no decimal; e.g., E103 Definitions, 402 Closed Funcitonality) are H3
- Subsections with decimals need IDs but will not use H

**Comment by RSD-accessboard** [comment]
I believe this is finished
