### ISSUE TITLE
Improve mobile rendering of Board Members page

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#382]
On my iPhone, the Board Member photos render next to their bios, instead of above the bio.  The result is that the bio is a narrow long / tall column of text with lots of empty space under photo.  The homepage Highlights do not exhibit this defect, and I thought they were using the same styling.

**Comment by RSD-accessboard** [comment]
I’ll be revisiting how the board members pages generated now that is going to use a collection from netlify, and will ensure it has mobile accessibility like the homepage

**Comment by RSD-accessboard** [comment]
working on this: check out /board-members/

**Comment by bruce-usab** [comment]
I see all the work on the Netlify back end.  The rendered Board Members page looks the same to me (even via preview from one of your recent branches) so I am guessing that is next?

And not to be a jerk, I think just lastname and firstname was enough fields.  To that, you have added fullname and filename.  OTOH, is is not like these need to get updated much.

**Comment by bruce-usab** [comment]
I especially like how you have enough data fields that the "past board members" page can be maintained from the same collection.

**Comment by bruce-usab** [comment]
Please make agency a drop-down menu.

**Comment by RSD-accessboard** [comment]
I think we can close this issue, we could put the agency drop-down list in a new post launch issue. If someone gets me all of the text separated by commas I’d be happy to just plug it in but it’s a bit tedious for me to go through and type it.

**Comment by bruce-usab** [comment]
Closed by PR https://github.com/atbcb/usab-uswds/pull/441

I created a new issue https://github.com/atbcb/usab-uswds/issues/451 for the agency drop-down.  I will provide you CSV text.
