### ISSUE TITLE
Add headings and 508 to DOJ's ADA-Standards

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#384]
_ADA/ADA-DOJ-standards.html

H3 tags need an ID, so I can create a link to them. Example `<h3 id="doj-intro">`

Some paragraphs should be converted to H3

After a navigation structure is created, this needs to get added into the table of contents

_Includes/table-of-contents-ADA.html

**Comment by bruce-usab** [comment]
I can probably help with this if you like.

**Comment by RSD-accessboard** [comment]
Sure, just wait for my pull request to go through
