### ISSUE TITLE
Left side nav is not sticking to the top on short pages

### ISSUE THREAD

**Issue by kengdoj** [atbcb/usab-uswds#385]
Example: https://beta.access-board.gov/mde/

**Comment by bruce-usab** [comment]
I actually think the behavior is okay.

**Comment by kengdoj** [comment]
This is a duplicate of an existing issue (not sure which though)

**Comment by RSD-accessboard** [comment]
this was fixed with universal layout and  all of the TOC is in the _includes/TOC/
