### ISSUE TITLE
It should be easier to get to TA phone number

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#396]
Francis expressed concern that she had to look and click a couple times to find phone numbers.

**Comment by bruce-usab** [comment]
From Francis initial impressions 9/9.  I think it is okay.

**Comment by RSD-accessboard** [comment]
TA phone number is already in contact us, maybe we can make it appear more prominent but I think that is the most likely place people will look

**Comment by bruce-usab** [comment]
The TA phone number is one click off the home page.  I think that is okay.  I understood Francis feedback to be that, with the old homepage, the phone number was right there in the footer.

**Comment by yanchulis** [comment]
I think it’s OK too.  We agreed to keep contact info centralized on the “contact us” page.

Dave

Dave Yanchulis
Director, Office of Technical and Information Services
U.S. Access Board
(202) 272-0026 (v), (202) 272-0027 (TTY)
yanchulis@access-board.gov<mailto:yanchulis@access-board.gov>
www.access-board.gov<http://www.access-board.gov>

**Comment by bruce-usab** [comment]
Closing this issue.
