### ISSUE TITLE
Improve website style

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#400]
Suggestions:

- [ ] Reduced space above the header, but below the US government site bar

- [x] Reduced size of standards font and blue banner

- [x] Reduce padding/margin of blue banner

- [ ] Consider having ADA/ABA be direct links from the homepage under the buildings-and-sites text

- [ ] change ADA/ABA guides table of contents to Ch 1: instead of Chapter 1:, or consider having submenu lists

**Comment by bruce-usab** [comment]
One other thing I would add to this is if we want more use of a red/rust banner color (.bg-secondary-darker) to distinguish News from Standards.
