### ISSUE TITLE
Landing page thumbnails should be circles

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#42]
We would like the small photos on the homepage to be circles instead of rectangles.

@RSD-accessboard thinks we can do this with CSS.  @bruce-usab thinks we will need to redo the images.

**Comment by RSD-accessboard** [comment]
Add a border radius
https://www.w3schools.com/css/css3_images.asp

USWDS has some preset border radius utilities. I think the rounded box might look better than a circle, and we can even add a shadow effects make it 3D looking

Randall Duchesneau III
US Access Board
1331 F Street NW, Suite 1000 ▪ Washington DC, 20004
(202) 272-0044
duchesneau@access-board.gov<mailto:duchesneau@access-board.gov>

Disclaimer: Technical assistance provided in this email is intended solely as informal guidance; it is neither a determination of your legal rights or responsibilities, nor a statement of the official views of the U.S. Access Board or any other federal agency.  Any links to non-federal websites are provided as a courtesy and do not represent an endorsement of the linked information, products, or services.

**Comment by RSD-accessboard** [comment]
reorganize as cards, Dave will provide new list i.e.  recreation is getting removed

**Comment by RSD-accessboard** [comment]
Turn them into circles in a branch, Dave did not like how it turned out. Probably will not pull into master. We will revisit homepage layout later
