### ISSUE TITLE
Standards and site navigation

### ISSUE THREAD

**Issue by jdschorr** [atbcb/usab-uswds#445]
The navigation for the ADA Standards section (https://beta.access-board.gov/ada/) is different than all the other sections.  All other section homepages (ABA, Passenger Vessels, etc) only show the the background and each navigation link leads to it's own page.  The ADA shows the entirety of the standards and navigation links jump to that portion of the Standards instead of a dedicated page.

A big downside of linking within the same page is that it's more difficult to get to the menus at the top of the page.  I eventually saw the "back to top" button, but it's not in a very intuitive place.

**Comment by bruce-usab** [comment]
Thanks for the feedback!

We are using a more advanced navigation mechanism on the ADA Standards.  The tentative plan was to upgrade the others to match it..

**Comment by bruce-usab** [comment]
May relate to issue https://github.com/atbcb/usab-uswds/issues/268

**Comment by RSD-accessboard** [comment]
closing this issue. We could revisit making the back to top button more apparent, but not sure what else we could do
