### ISSUE TITLE
Language for guide pdf links

### ISSUE THREAD

**Issue by jdschorr** [atbcb/usab-uswds#446]
For the guides to the Standards, almost chapters sections state what the "Download" button links to (eg. "PDF version of Chapter 10 Play Areas Guide").  The chapters for "Play Surfaces" and "Swimming Pools, Wading Pools, and Spas" are only labeled as "PDF version".
[https://beta.access-board.gov/ada/guides/chapter-10-play-surfaces/]
[https://beta.access-board.gov/ada/guides/chapter-10-swimming-pools-wading-pools-and-spas/]

**Comment by bruce-usab** [comment]
Thanks, good catch!
