### ISSUE TITLE
About, File a Complaint, Research, Contact Us -- do not match News and Guidelines and Standards

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#450]
Earlier parts of the website (About menu, Research, Contact Us, File a complaint) do not visually match the newer and more developed sections of the website (namely Guidelines and Standards, but also News [which _is_ from the original template]).

This task is update the default styling to the basic page layout has something other than an white gap between the menu and body content.  Probably just a dark blue bar would be enough to get us started.  But we might want to revisit this issue later.

**Comment by RSD-accessboard** [comment]
this is done with universal layout and page layout. You can use banner-title: in the front matter
