### ISSUE TITLE
Board Members page Netlify UI should use drop down list for federal members

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#451]
Since it is a fixed list, the federal agency fields should be a drop down list in Netlify UI.  The agency name should be generated from the federal abbreviation (or vice versa).
- [x] Bruce need to provide the list as csv.

**Comment by bruce-usab** [comment]
Color in hover-text are fine.  Here is the tool I use, which helpfully has the option to generate a permalink!
[webaim.org/resources/contrastchecker/?fcolor=005EA2&bcolor=D9E8F6](https://webaim.org/resources/contrastchecker/?fcolor=005EA2&amp;bcolor=D9E8F6)

**Comment by RSD-accessboard** [comment]
mobile rendering looks fine and it is a drop-down list in netlify
