### ISSUE TITLE
Board Members images not rendering in GitHub preview

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#456]
Board Members images are shown as broken link when using GitHub branch preview.  From inspection, images are using an absolute URL, so probably just missing {{ site.baseurl }} some place.

**Comment by RSD-accessboard** [comment]
This is an overall issue with {{ site.baseurl }}

Same reason the links Are not working for you, The pictures also don’t show in the branch build. But everything shows up in the beta

I don’t think this issue means that important since you can upload the pictures and See them in netlify

**Comment by bruce-usab** [comment]
Good point that it is not a problem for Netlify, which will be the main back-end UI for this content.

But it is weird because the individual Board Member pages hand no problem with the images rendering, and they are using the same `uploads` directory !

FWIW, the problem I was having Friday turned out to be [PEBCAK](https://www.google.com/search?q=pebcak)

**Comment by RSD-accessboard** [comment]
Lol that’s a new one for me
problem exists between chair and keyboard
