### ISSUE TITLE
Update Contact Us page

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#460]
Contact us page is looking a bit shabby as compared to everything else!  (I was perfectly happy with it a couple of weeks ago.)
- [ ] A couple lines are indented instead of flush left
- [x] might better be tables rather than lists
- [x] map at bottom broken

**Comment by bruce-usab** [comment]
- headers are all coded the same, so I have no idea why they are rendering differently!
- page is already using tables
- fixed map

**Comment by bruce-usab** [comment]
I can live with Contact-Us pages as-is.

**Comment by RSD-accessboard** [comment]
we should revisit this and completely redo the styling to make it more modern. Probably should do this before we go live
