### ISSUE TITLE
Netlify UI for 504 contacts

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#461]
@RSD-accessboard has created Netlify back-end, but we
- [x] we still need to add all the content
- [x] verify the index page rendering
- [x] change public facing page to use rendered version

See # https://github.com/atbcb/usab-uswds/issues/363.  Currently site is using old hand-coded list.

**Comment by bruce-usab** [comment]
@bstinnette would you be willing to work on the data entry?

**Comment by bstinnette** [comment]
Yes, I can work on the data entry for the 504 contacts.

**Comment by bstinnette** [comment]
I added all 504 contacts.
