### ISSUE TITLE
Enforcement might benefit from its own set of menus

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#462]
I really like how the Spanish pages work together with their own small sett of menus.  Should the few File-an-ABA-Complaint and related Enforcement pages get a similar treatment?

P.S., Just looking for feedback, not volunteers!

**Comment by philbratta** [comment]
I agree, and I think those mentioned pages would be better with a TOC on the left-hand side. My only hesitation regards the number of items in that side menu. How many would be there for each page?

**Comment by bruce-usab** [comment]
The En Español collection is nine pages.  I feel like that is just about the right number.
https://beta.access-board.gov/es/

The Enforcement stuff is just five pages at the moment, so it is a little light to be a collection.

**Comment by philbratta** [comment]
Yes, nine is a solid number, although I also think five would work without making the page oddly designed in any way. I'm on board with the change.

**Comment by bruce-usab** [comment]
It would also be good to break up docs in the About menu into collections.  But it is a conundrum as to where to stash them.  After launch, we expect to be able to use beta.access-board.gov for a development url.

I am thinking the About menu could work more like the Guidelines and Standards menu.  So, for example, Laws and Policies could each be it own collection, similar to haw ICT, ADA, ABA are each their own section.

**Comment by philbratta** [comment]
I agree, and that reminds me that that was the last comment I meant to leave on the feedback: https://usaccessboard.sharepoint.com/:w:/r/sites/OTIS/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B91ECF1B4-16FC-4FC2-A35D-D9CC433EC524%7D

The About tab/splash page has so many subheadings/pages in its TOC. And I think you hit the nail on the head with organizing it along four main categories: About, Budget and Performance, Laws, Policies. Similar to the Guidelines and Standards tab, the About tab should have a drop-down menu of these nestled categories (and their subsequent pages).

**Comment by mariodamianiUSAB** [comment]
I agree with your suggestion, Bruce.
