### ISSUE TITLE
Single file versions

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#464]
Make sure we have single file versions for all guidelines and standards

- [x] ADA
- [x] ABA (make a single file KMS version at the same time?)
- [ ] Vehicles
- [ ] rights-of-way
- [ ] MDE
- [ ] passenger vessels

This might be done by creating a page that loops through the collection, and we can add a link to the single file version in the layout

**Comment by kengdoj** [comment]
ICT, ABA, ADA done. Revisit for others another day.
