### ISSUE TITLE
Breadcrumbs?

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#465]
Christopher Hart likes the breadcrumbs… Should we add this feature back in?

**Comment by bruce-usab** [comment]
If we get the feature programmatically.  I asked at the very beginning (answer was no) but that was before Andrew was on board.

Seems like it should be reasonably easy, since the sitemap function is working.

**Comment by bruce-usab** [comment]
Check this out, new with [v2.8.0 (July 2020):](https://designsystem.digital.gov/about/releases/#version-280)
[designsystem.digital.gov/components/breadcrumb](https://designsystem.digital.gov/components/breadcrumb/)
