### ISSUE TITLE
Simplified view toggle button

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#466]
Should we create a button in the header that toggles you to mobile mode for easier reading for people with cognitive disabilities?

**Comment by bruce-usab** [comment]
Lets think about it and discuss more.  I can see pros and cons.

Pros:  
- I would like to have the manual option myself
- As a general rule, it almost always good to add coga features when possible
-- shrinking the window is not an obvious way to trigger the desired UI behavior

Cons:  
- It is one more control on the page, so adding an explicit UI makes the page more complex
-- The page being more complex makes it harder for coga folks!
