### ISSUE TITLE
MDE Preamble links

### ISSUE THREAD

**Issue by kengdoj** [atbcb/usab-uswds#469]
The [MDE Preamble page](https://beta.access-board.gov/mde/preamble/) has links that are broken/need updating. (This is not a fully inclusive list. It would be helpful if someone went through the page to identify the updates.)

Some links go to current site. Do you want these pages migrated?

- >The online version of the final rule, as well as other materials related to this rulemaking, can be found here http://www.access-board.gov/guidelines-and-standards/health-care/about-this-rulemaking.
- >The transcript of the meeting is available at https://www.access-board.gov/guidelines-and-standards/health-care/about-this-rulemaking/background/public-information-meeting.

- > FOR FURTHER INFORMATION CONTACT: Earlene Sesker, U.S. Access Board, 1331 F Street, NW, Suite 1000, Washington, DC 20004-1111. Telephone numbers: 202-272-0022 (voice) or 202-272-0091 (TTY). E-mail address: sesker@access-board.gov. Or Rex Pace, U.S. Access Board, 1331 F Street, NW, Suite 1000, Washington, DC 20004-1111. Telephone numbers: 202-272-0023 (voice) or 202-272-0050 (TTY). E-mail address: pace@access-board.gov.

- >The MDE Advisory Committee recommended a high transfer height of at least 25 inches and recommended that the transfer surface be adjustable in small, virtually continuous increments. MDE Advisory Committee Report, 67-71, available at https://www.access-board.gov/guidelines-and-standards/health-care/about-this-rulemaking/advisory-committee-final-report. 

  - >MDE Advisory Committee Report, 69, available at https://www.access-board.gov/guidelines-and-standards/health-care/about-this-rulemaking/advisory-committee-final-report.
  - > MDE Advisory Committee Report, 68, available at https://www.access-board.gov/guidelines-and-standards/health-care/about-this-rulemaking/advisory-committee-final-report.
  - > MDE Advisory Committee Report, 71, available at https://www.access-board.gov/guidelines-and-standards/health-care/about-this-rulemaking/advisory-committee-final-report. 

- >  (The minority reports are available at https://www.access-board.gov/guidelines-and-standards/health-care/about-this-rulemaking/advisory-committee-final-report/appendix-a-minority-reports).

  - > The minority reports submitted by the disability advocates and academics supported a minimum low height of 17 inches. See Minority Reports from Boston Center for Independent Living Inc., National Network for ADA Centers, and Medical Diagnostic Equipment Advisory Committee,7 available at https://www.access-board.gov/guidelines-and-standards/health-care/about-this-rulemaking/advisory-committee-final-report/appendix-a-minority-reports. 

  - > Minority Report from National Council on Independent Living (Sept. 27, 2013), available at https://www.access-board.gov/guidelines-and-standards/health-care/about-this-rulemaking/advisory-committee-final-report/appendix-a-minority-reports.

  - > The minority reports submitted by manufacturers supported a minimum low height of 19 inches. See Minority Reports from Hologic, Inc., Midmark Corporation, MITA Advisory Committee Members,8 and Recommendation of 19-inch Lower Adjustable Height as the Minimum Accessibility Standard (Joint Report),9 available at https://www.access-board.gov/guidelines-and-standards/health-care/about-this-rulemaking/advisory-committee-final-report/appendix-a-minority-reports. 

- >  http://www.aami.org/he75

- > http://www.udeworld.com/anthropometrics.html

- > Scales that can be wall mounted or that are portable would facilitate where there are space constraints.” Subcommittee Report – Weight Scales, 7, available at https://www.access-board.gov/guidelines-and-standards/health-care/about-this-rulemaking/advisory-committee-final-report/appendix-b-supporting-documents.

**Comment by bruce-usab** [comment]
Thanks for flagging this!
