### ISSUE TITLE
ADA/ABA guides side navigation

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#47]
consider doing ADA and ABA guides side navigation as a data file with 3 levels of side navigation, so that way all of the guides under chapter 4 can be grouped under a chapter 4 accordion etc. all of chapter 10 guides can be grouped under chapter 10

**Comment by bruce-usab** [comment]
Tutorial example include three tier navigation: https://jekyllrb.com/tutorials/navigation/

**Comment by bruce-usab** [comment]
Later related issues include https://github.com/atbcb/usab-uswds/issues/268 and https://github.com/atbcb/usab-uswds/issues/445
