### ISSUE TITLE
Are Guide documents and animations easy enough to find?

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#503]
I am troubled that the animations and guides are not easier to find.  I don't have any good suggestions, as it is logical how we have things structured.

It also seems to me that how the guides relate to each other might benefit from being promoted throughout the guide chapters.

I love this graphic:
![chapter 2 at center of wheel](https://beta.access-board.gov/images/ada-aba/guides/chapter2-aba/nc2.jpg)

Could/should this be the basis of a navigation mechanism?  If so, could/should we add a version with Chapter three having three branches, and Chapter Four five branches, Chapter 5 two branches, etc.

**Comment by philbratta** [comment]
Hi Bruce, is this an issue you want me to address now, or is it for, as indicated, after the launch? I can do either, but I want to verify as well as avoid any perceived gesture that I left you hanging by not responding now. I'm happy to offer my feedback sooner than later if that's needed.

**Comment by bruce-usab** [comment]
Issues by category are sorted into projects by priority (high to low):

- Minimal Viable Product (should already be done, not all are)
- post beta launch (where we are now, still lots to of details to work through)
- post www launch (like this item)
- stuff that can be put off until 2021, but that we don't want to loose track of

I have not put much time/effort into sorting issues (within each project) by priority.  GitHub UI promotes the practice of having more important issues higher/above less crucial issues.  See:  
https://github.com/atbcb/usab-uswds/projects/2

This particular issue is something that will have to wait (for implementation) until after the launch.  But I think it is something that we might want to revisit before very long.  Feedback sooner than later is welcome. 

In my mind, missing-but-obscure stuff is a higher priority for the next couple of weeks.

**Comment by bruce-usab** [comment]
We will be discussing 11-19.

I created a pull request implementing [ADA Guides and Animations in the secondary menu](https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/preview/atbcb/usab-uswds/bruce-adds2secondary/) in `_config.yaml`

I do **not** think it is great.  I do like that the Guides and Animations are available _on every page_ and not just the home page.
