### ISSUE TITLE
Guide pages have titles in quotation marks

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#518]
I just noticed that some of the guide .md pages, in the front matter, have quotation marks around the page title.  Doesn't seem to be effecting anything...

**Comment by bruce-usab** [comment]
Discovered today that the Guide .md pages require the quote marks or things break.

Titles in \_pages and \_posts do not use quote marks, so it seems bad to me to have them required for other collections.

**Comment by RSD-accessboard** [comment]
You need quotes there any special characters in the front matter.
