### ISSUE TITLE
ICT Preamble internal links do not work

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#522]
The ICT Preamble is a long file with internal links and mini-TOC which do not work post migration.  Those links need to corrected, using HTML style ID tags and/or by updating HREF values.

- Source page is [_ict/preamble.html](https://github.com/atbcb/usab-uswds/blob/master/_ict/preamble.html)
- Rendered page is [{{ site.baseurl }}/ict/preable/](https://beta.access-board.gov/ict/preamble/)

**Comment by kengdoj** [comment]
PR #520 fixed the headings.
