### ISSUE TITLE
Missing guides

### ISSUE THREAD

**Issue by jdschorr** [atbcb/usab-uswds#549]
ABA ramps:
Link is:
https://beta.access-board.gov/files/ada-aba/guides/aba/ramps.pdf
Link should be:
https://beta.access-board.gov/files/ada-aba/guides/aba/ramps-ABA.pdf

ABA Drinking Fountains, ABA Toilet Rooms, ABA Bathing Rooms: nothing there

**Comment by jdschorr** [comment]
meant to include they were from their respective https://beta.access-board.gov/aba/guides/ pages

**Comment by bruce-usab** [comment]
Understood!  Thanks for spotting this.
