### ISSUE TITLE
missing guidance

### ISSUE THREAD

**Issue by jdschorr** [atbcb/usab-uswds#552]
All of this was accessed through https://beta.access-board.gov/guidance.html (the "Guidance Documents" link at the bottom of every page)

https://beta.access-board.gov/aba/guides/chapter-3-protruding-objects/ - no link to pdf download

missing all links to both html and pdf for:

Guide to the ABA Standards: Accessible Routes (HTML) PDF (July 2015)
Guide to the ABA Standards: Entrances, Doors, and Gates (HTML) PDF (July 2015)
Guide to the ABA Standards: Ramps and Curb Ramps (HTML) PDF (July 2015)
Guide to the ABA Standards: Elevators and Platform Lifts (HTML) PDF (July 2015)
Guide to the ABA Standards: Accessible Means of Egress (HTML) PDF (July 2015)
Guide to the ABA Standards: Parking Spaces (HTML) PDF (May 2016)
Guide to the ABA Standards: Passenger Loading Zones (HTML) PDF (May 2016)
Guide to the ABA Standards: Stairways (HTML) PDF (May 2016)
Guide to the ABA Standards: Drinking Fountains (HTML) PDF (May 2020)
Guide to the ABA Standards: Toilet Rooms (HTML) PDF (May 2020)
Guide to the ABA Standards: Bathing Rooms (HTML) PDF (May 2020)
Outdoor Developed Areas: A Summary of Accessibility Standards for Federal Outdoor Developed Areas (HTML) PDF (May 2014)

Guides to the ADA Guidelines for Transportation Vehicles (HTML) (October 1992)
Guide to the Section 508 Standards (HTML) (June 2001)
Guidance on the Telecommunications Act Section 255 Guidelines (HTML) (April 1999)

Accessible Public Rights-of-Way: Planning and Designing for Alterations (HTML) PDF (August 2007)
Detectable Warnings Update (HTML) PDF (May 2014)
Accessible Sidewalks (video) (2003)

Best Practices for Making Prescription Drug Container Label Information Accessible to Persons Who are Blind or Visually-Impaired or Who are Elderly (HTML) (July 2013)

**Comment by bruce-usab** [comment]
Still working on this Guidance Document page...

**Comment by bruce-usab** [comment]
Same issues as https://github.com/atbcb/usab-uswds/issues/374

**Comment by bruce-usab** [comment]
closed by https://github.com/atbcb/usab-uswds/pull/557
