### ISSUE TITLE
Homepage and header tweaks

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#561]
Motto in red looks good!
- [ ] star logo should be a little bigger
- [ ] text size of "U.S. Access Board" should be a little bigger or motto font size a little smaller
- [ ] vertical gap between highlights and text at bottom "The U.S. Access Board is a ..." should be less

(Feedback from DY 9/22)

**Comment by RSD-accessboard** [comment]
Yeah, I wanted to tweak all those things to… Wish it was easier to do. Using these flex boxes is a bit confusing
