### ISSUE TITLE
Board member bio & photo update:  Mark Schultz 

### ISSUE THREAD

**Issue by yanchulis** [atbcb/usab-uswds#562]
![schultz-ed](https://user-images.githubusercontent.com/64024171/93915113-86eaf480-fcd5-11ea-8065-c61d0028993d.PNG)
The bio and photo for Federal member Mark Allan Schultz (ED) need to updated with the text below and attached photo:

Mark Allan Schultz is the Rehabilitation Services Administration (RSA) Commissioner at the U.S. Department of Education and has been delegated the authority to perform the functions and duties of the Assistant Secretary of the Office of Special Education and Rehabilitative Services. RSA assists states and other agencies in their work to provide vocational rehabilitation and other services to individuals with disabilities to maximize their employment, independence and integration into the community and the competitive labor market. Schultz previously served as a deputy commissioner at the Nebraska Department of Education. He also served as both the director and associate director of Nebraska Vocational Rehabilitation, as director of the Nebraska Assistive Technology Partnership, and as a barrier-free design specialist for the League of Human Dignity, a Center for Independent Living. He was president of the Council of State Administrators of Vocational Rehabilitation and a member of the Workforce Innovation and Opportunity Act Information Technology Steering Committee. Schultz received a bachelor’s in architectural studies from the University of Nebraska, Lincoln and a master’s in public administration from the University of Nebraska, Omaha.

**Comment by bruce-usab** [comment]
@yanchulis if we get more updated photos or bios, please checkout the slick Netlify @RSD-accessboard UI developed!

- add `/admin` to the URL, so https://beta.access-board.gov/admin
- pick "Board Members" from the left sidebar Collections menu
- follow fields and prompts on the next screen to update or add Board Members

Yes, we still need to add City, State field for Public Board Members.

**Comment by yanchulis** [comment]
Sweet!  I will enter any other member updates that come in.

Dave

Dave Yanchulis
Director, Office of Technical and Information Services
U.S. Access Board
(202) 272-0026 (v), (202) 272-0027 (TTY)
yanchulis@access-board.gov<mailto:yanchulis@access-board.gov>
www.access-board.gov<http://www.access-board.gov>
