### ISSUE TITLE
Page title is broken

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#570]
The page title that shows up in the browser tab is broken. It has the same page title for all pages. This was working, not sure when it broke.

**Comment by kengdoj** [comment]
The Training & Webinars and News pages seem to have this problem. The others seem ok.

**Comment by bruce-usab** [comment]
Oops, we forgot to Ask Andrew about this today.

**Comment by bruce-usab** [comment]
Board Members page also does this.  I will ping Andrew.

**Comment by kengdoj** [comment]
For the Training & Webinars and News pages, the page title should be Training & Webinars and News, respectively. Seems like these pages should use the same technique the page title is created on Research and Contact us/other pages that do not have the top blue banner. Is this correct?

**Comment by bruce-usab** [comment]
Yes @kengdoj on all points

**Comment by bruce-usab** [comment]
Looking at https://github.com/atbcb/usab-uswds/pull/378 before I ping Andrew.

**Comment by RSD-accessboard** [comment]
It’s possible there has been no page.title assigned. If the front matter variables not defined. I think we can figure this out without Andrew

**Comment by kengdoj** [comment]
Why do some pages have the blue banner and others don't?

**Comment by RSD-accessboard** [comment]
It depends on which layout they’re using. I created that blue banner for the layouts I made, and ended up looking so nice we started using them more and more across the site. We can change the _Layouts/page 2 also use the blue banner

**Comment by kengdoj** [comment]
I like the blue banner. I'd like to see it on all pages if that makes sense

**Comment by bruce-usab** [comment]
i agree the blue banner looks sharp
the field populating the blue banner is not consistent though
sometimes it is title, other times collection title, other times something else

wrt OP, i am not finding missing title attributes, but I will keep looking

**Comment by bruce-usab** [comment]
My working theory is that front matter in .html pages does not do anything.  We have webinars/index.htm and news/index.html and the latter was built off the USWDS template, but it is only these two pages which seem to have the bad behavior.

I will test in a local build on my VM.

**Comment by RSD-accessboard** [comment]
Front matter does work in.html pages otherwise we wouldn’t be able to give them a layout.

Trainings and webinars and news are funny though because they are created with pagination. That could be something that is messing them up

**Comment by bruce-usab** [comment]
Good point about front matter giving html pages a layout.

Initial results from converting /news/index.html and /webinars/index.html to \_pages/news.md and webinars.md

- Scary warning that "Pagination: Is enabled, but I couldn't find any pagination page. Skipping pagination."
- News articles fail to generate articles, which is not entirely unexpected given the scary warning.
- Webinars page generates same as before
- Both News and Webinars still have bad titles

**Comment by bruce-usab** [comment]
Blah, just wasting time.  News articles in News page are not generating on my local build.

**Comment by kengdoj** [comment]
PR #582 fixes the titles for the Board members, News main page, Training & Webinars main page.

Where are the **webinar pages** like https://beta.access-board.gov/2020/09/02/webinar-ability-center-of-greater-toledo/ 

and **news pages** like https://beta.access-board.gov/2020/09/02/webinar-national-park-service-regions-3-4-5-accessibility-workshop/?

**Comment by bruce-usab** [comment]
Nice.  Just found this doc that paginator pages should not have a permalink:
https://jekyllrb.com/docs/pagination/

**Comment by bruce-usab** [comment]
LOL, now home page title is title from blog post with oldest date.  I will add the `document.title={{page.title}}` JavaScript in my branch to patch that.

**Comment by RSD-accessboard** [comment]
They are all under_posts\
