### ISSUE TITLE
Upgrade ICT pages to single page version w/ Enhanced navigation

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#590]
Per conversation 9-25, @yanchulis would like to for the ABA and ICT standards to use the same navigation we have with the ADA standards.
- [ ] port ICT single page version from in-house KMS
- [ ] apply ADA left sidebar navigation to ICT rule
- [ ] fix all the many little things that break
- [ ] text and compare single page version to current collection version (12 pages)
- [ ] replace and wave goodbye to the version which was so hard for @bruce-usab !

**Comment by kengdoj** [comment]
PR #645 closes this issue.
