### ISSUE TITLE
Add destination for "back to top" links 

### ISSUE THREAD

**Issue by kengdoj** [atbcb/usab-uswds#64]
All of the ada guides page need a destination before the **Chapter heading** in the main content area for same page link at bottom: [Back to top](#top)

**Comment by RSD-accessboard** [comment]
I was just getting rid of them

**Comment by kengdoj** [comment]
getting rid of the "back to top" links?

**Comment by RSD-accessboard** [comment]
Yes, just get rid of them. If we want that functionality I can create a generic one and put into the _layout/Standards so it works on every single page on the website Using that layout

**Comment by bruce-usab** [comment]
I agree with getting rid of the "back to top" links!  I am not sure when we started doing that.  BtW, on Windows, the Home key does about the same thing (except that it does not move focus, and Home jumps to very top of page, not top of content).

**Comment by kengdoj** [comment]
ok, removing the back to top links from the bottom
