### ISSUE TITLE
Please check duplicate link names on Chapter-4-entrances-and gates

### ISSUE THREAD

**Issue by kengdoj** [atbcb/usab-uswds#67]
At bottom half of https://www.access-board.gov/guidelines-and-standards/buildings-and-sites/about-the-ada-standards/guide-to-the-ada-standards/chapter-4-entrances,-doors,-and-gates:

> Communication Access at Doors [[§806.3.2](https://www.access-board.gov/guidelines-and-standards/buildings-and-sites/about-the-ada-standards/ada-standards/chapter-8-special-rooms,-spaces,-and-elements#806%20Transient%20Lodging%20Guest%20Rooms), [§806.3.2](https://www.access-board.gov/guidelines-and-standards/buildings-and-sites/about-the-ada-standards/ada-standards/chapter-8-special-rooms,-spaces,-and-elements#809%20Residential%20Dwelling%20Units)]

The second link goes to 809. What should the second link name be?

**Comment by RSD-accessboard** [comment]
809.5

**Comment by kengdoj** [comment]
Thanks!
