### ISSUE TITLE
UFAS, 1991 STANDARDS CLEANUP

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#682]
need to clean up HTML of _ADA/ADAAG-1991-2002.html

There is unnecessary use of definition list definition term which is being bolded for some reason. Replace with headings and paragraphs

For Kathy or possibly Sarah

**Comment by kengdoj** [comment]
@RSD-accessboard, @bruce-usab  - please check if Sarah can take this? the PVAG pages require a LOT of time to fix.

**Comment by kengdoj** [comment]
https://www.access-board.gov/aba/ufas.html

**Comment by kengdoj** [comment]
@RSD-accessboard - do we have the original page for reference? What's the Facilities section under https://www.access-board.gov/aba/ufas.html#414-occupancy-classifications supposed to look like?

**Comment by bruce-usab** [comment]
Definition lists is the correct formatting to be using for our glossaries, and the syntax is supported by markdown.

I am all for adjusting the default presentation effects for `DL` , `DT` , `DD`.

**Comment by bruce-usab** [comment]
For the original page for reference, I have been using the [WayBack Machine](http://web.archive.org/web/20201016182838/www.access-board.gov).  I use the PDF version when I can find it, and infer the HTML elements from the visual rendering.  The HTML versions from the old site are not canonical, but merely<q>good enough</q>, and mostly do **not** pay good attention to semantic HMLT.   Here is the [old version of 4.1.4 Occupancy Classifications](https://web.archive.org/web/20201016182838/https://www.access-board.gov/guidelines-and-standards/buildings-and-sites/about-the-aba-standards/ufas#4.1.4).

**Comment by kengdoj** [comment]
There are **lists** on this page, like under https://www.access-board.gov/aba/ufas.html#411-accessible-sites-and-exterior-facilities-new-construction. 

But there's no available list style with parenthesis before and after the number/letter. Can we change the appearance of these numbered lists?

**Comment by bruce-usab** [comment]
Yes, we can change the appearance of numbered lists.  That has been done many times for many different documents.  Not only does the use of parenthesis vary, but also indentation.

We

**Comment by kengdoj** [comment]
PR #906 - UFAS page and toc fixed
