### ISSUE TITLE
List structure needed but can the number style be modified?

### ISSUE THREAD

**Issue by kengdoj** [atbcb/usab-uswds#728]
[DOJ's ADA Title II](https://beta.access-board.gov/ada/#doj-title-2) and [Title III](https://beta.access-board.gov/ada/#doj-title-3) have outlines without correct list structure. 

But, the list style for `<ol>` do not include parenthesis, e.g., (1). Can the number style be changed to a [default style](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol)?

**Comment by bruce-usab** [comment]
Good catch.  I think we should us OL even if CSS does not give granular control over the parenthesis/decimal formatting.

**Comment by RSD-accessboard** [comment]
I think this  when we should  confirm with Dave  before pulling into master because I heard DOJ was  very touchy about us putting their ADA regulations on our website. Will  probably need to make sure there's absolutely no changes to content or language

**Comment by bruce-usab** [comment]
I was there for some of those conversations.  This sort of minutia is not where DOJ sensitives laid, but I have no problem pinging @yanchulis before someone starts on this.
