### ISSUE TITLE
Fun with CSS a.k.a.  ask Andrew

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#733]
- [x]  liquid text does not always render, example barriers act big button to guides on about page
- [ ] right side universal sticky and maximum height  viewport, how to get it so the pictures resize keep right side  navigation from overflowing
- [ ] left side navigation table of contents uses entire viewport in mobile mode,  reduce to smaller @Media
- [ ]  fix anchor link styling

**Comment by bruce-usab** [comment]
These are all good and tricky, -- but I have to say I love seeing the issue count come down!

**Comment by RSD-accessboard** [comment]
- [ ] redirect links (.html needed)

**Comment by bruce-usab** [comment]
@RSD-accessboard pls review, i think these might be done

**Comment by RSD-accessboard** [comment]
3 things At the top I still need help from Andrew with

**Comment by bruce-usab** [comment]
Okay, thanks!
