### ISSUE TITLE
Action Items from Call 11-10

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#753]
- [x] @bruce-usab to update menu and highights to use ICT as main abbr
- [x] @philbratta to delete author names from news articles
- [x] @RSD-accessboard add right-side contact email/phone to training and research landing pages
- [ ] @RSD-accessboard enhancements to 504 contacts
- Alphabetize by full name
- Add back-end fields for date last updated
- make web link live
- [x] @bruce-usab to trim down ICT landing page
- [x] @RSD-accessboard to remove phone numbers from Contact Us page and put accordions around other sections
<del>- [ ] @RSD-accessboard to make outer div on highlights page to be selectable (so image, title, and description are all one link)</del>
- [ ] @RSD-accessboard swap out blue laptop webinar guy for TA sidebar icon
- [x] @RSD-accessboard find research icon (cash flow statement)
- [ ] @RSD-accessboard to universal layout to about pages and see if that improves wide tables (as with FOIA annual report).

**Comment by RSD-accessboard** [comment]
Putting homepage link on the outer div not that easy, Messes up all the styling

**Comment by bruce-usab** [comment]
Thanks for trying, that was pretty low priority my mind.  Certainly we do not three links (graphic, title, sentence) to the same URL, all one right after another.
