### ISSUE TITLE
Add GovDelivery email subscription links as needed

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#765]
@bruce-usab tried to add a GovDelivery email subscribe box to the [ICT about page](https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/preview/atbcb/usab-uswds/bruce-email-subscriptions/ict/).  It didn't work.

Added the content [here](https://github.com/atbcb/usab-uswds/blob/bruce-email-subscriptions/_includes/sidenav-508.html) and [there](https://github.com/atbcb/usab-uswds/blob/bruce-email-subscriptions/_includes/technical-assistance-508.html) to no effect.

@RSD-accessboard, please hit me with a clue bat.

**Comment by RSD-accessboard** [comment]
Gov delivery is now an Include that can be used across the website, And is working

**Comment by bruce-usab** [comment]
Thanks @RSD-accessboard !
