### ISSUE TITLE
ICT Standards not quite rendering correctly

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#791]
The [ICT standards](https://www.access-board.gov/ict/) are not presenting quite correct.

1. Additional Resources is not in the TOC.  I cannot figure out why.
2. The PDF link is not working correctly.  I added `file` in front matter, but only in the `about.md` page.  Worse than that, it seems to me that the PDF button links incorrectly if the document is scrolled down.  I don't have circumstances worked out exactly.

**Comment by kengdoj** [comment]
1. I'll add Additional Resources. The TOC was manually created.
2. The PDF link - meaning the button at the top of the page?

**Comment by bruce-usab** [comment]
@kengdoj fixed (1).

@RSD-accessboard, please see if [line 8 in ict-single](https://github.com/atbcb/usab-uswds/blob/master/_ict/ict-single.html) is correct.  Is it suppose to have a path?

( fwiw, PDF file _is_ loading -- but only because I copied it from `/files/ict` to `/_pages/ict` )
