### ISSUE TITLE
Animations and guides on homepage

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#810]
Proposal- received feedback From Capozzi and users about hard-to-find guides and animations, suggested to have on homepage

**Comment by bruce-usab** [comment]
I want them available elsewhere too.

How about adding to secondary nav?  (Currently just En Español.)  Or one more primary nav item (Animations and Guides, with two drop-downs)?

**Comment by bruce-usab** [comment]
Previously mentioned in #503

**Comment by bruce-usab** [comment]
Proposals from discussion 11-19:
1. Add to secondary menu (Dave not a fan)
2. Four Cards under highlights
3. Accessibility Animations film reel on Hero.

**Comment by bruce-usab** [comment]
Action item:
1. Add hero-like film strip featuring three or four direct link to particular animation.  Center (film strip) or title will read <a>accessibility animations</a>
