### ISSUE TITLE
Redirects from guides issue (both ABA and ADA)

### ISSUE THREAD

**Issue by jdschorr** [atbcb/usab-uswds#843]
All of the links from the ADA guides that point to specific subsections of the Standards don't link properly.  It only doesn't work if there is one level of sub-section, but is fine if even more specific.
Here's what I mean (using examples from ADA Parking Guide)
-Links to a whole section work (eg "§208") and direct to the proper place in the ADA
-Links with a single sub-section do not work (eg "§208.3") and directs to the default ADA page
     >links to "https://www.access-board.gov/ada/#208.3-Location" instead of "https://www.access-board.gov/ada/#ada-208_3"
-Links with a sub-sub-section do work (eg §208.2.1) and direct to the exact spot on the ADA

Bigger issue and easier to describe: none of the links to the ABA from the ABA guides work.  Every section link gets a 404 message.
For example: §F208 (in ABA parking guide) goes to: "https://www.access-board.gov/aba/ch02/#F208-Parking-Spaces" instead of "https://www.access-board.gov/aba/#aba-f208"

**Comment by RSD-accessboard** [comment]
This should all be fixed now. If there still are links that are not working, please send Specific examples
