### ISSUE TITLE
Break ict-single.md into multiple files

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#849]
I think it would be easier to maintain, and more consistent with how ADAAG/ABAAS are constructed, if the ICT chapters were each their own file.  Right now, just About and Appendix D are stand-alone files and everything else is inside ict-single.html.  I would like for ict-single.html to just pull chapter-based files into a unified presentation.

Also www.access-board.gov/ict/ and www.access-board.gov/ict/about.html present a little differently.

This is not a high priority.

**Comment by kengdoj** [comment]
I don't think breaking into multiple files makes for easier maintenance if the same change has to be made to multiple files. What is driving this suggestion?

**Comment by bruce-usab** [comment]
1. I find it easier to to deal with smaller files than larger files
2. VSC makes it pretty easy to make the same change in multiple files
3. I think it would be much better for 508 to have the same file structure as ADAAG and ABAAS

**Comment by bruce-usab** [comment]
Per conversation today, the single file versions of ADAAG and ABAAS are also using monolithic files instead of a chapter-by-chapter approach.
