### ISSUE TITLE
ICT landing page needs work

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#859]
I would like to nominate @philbratta to take an editorial pass at the [ICT landing page](https://www.access-board.gov/ict.html) off the home page.

Ideally, probably, the ICT link from the homepage would go straight to [/ict/](https://www.access-board.gov/ict/).  But jumping right into the standards is a bit much for someone who might not even be in the right place.

The ICT landing pages aims to clarify not just between old and new 508, but also between new 508 and old 255.  @bruce-usab thinks that seems like a bit too much work, and a bit too particular, for the [About section of /ict/](https://www.access-board.gov/ict/#about-the-ict-accessibility-standards)

The current ICT landing page (1) is too long, and (2) overlaps too much with that About section.  We are aiming for something terse as with the [Buildings landing page](https://www.access-board.gov/buildings.html).

**Comment by philbratta** [comment]
@bruce-usab -- I have drafted a more concise ICT landing page. Would you like that draft here or in an email or entered into a pull request?

**Comment by philbratta** [comment]
All set with this landing page. I previewed it and spoke with Randall who helped with making sure the Section 508 heading hyperlink would go to the correct place. Let me know if you need anything else.

**Comment by philbratta** [comment]
@bruce-usab Also, Randall already pulled the changes into Master.

**Comment by bruce-usab** [comment]
Okay, that explains why I could not find a preview!

@RSD-accessboard please revert.  Do not pull into master until I get a chance to review.

The difficulty is that we do **_not_** really want to be promoting the [revised 255 guidelines](https://www.access-board.gov/ict/#255ch1) until FCC adopts them.

People need pointers to three things:  (1) The old 508 standards, (2) the new 508 standards, and (3) the old 255 guidelines.

**Comment by philbratta** [comment]
So, do you want me to rethink my draft with these three pointers in mind? My apologies, but I didn't know that these three pointers need to be part of that landing page.

**Comment by bruce-usab** [comment]
Yes please.

FWIW, I can't figure out where your edits are!

The old page is still live:  https://www.access-board.gov/ict.html

There are only the three links/pointers from that page now.  I just don't think the prose does a great job explaining things, and it seems overly long for what it needs to do.

**Comment by bruce-usab** [comment]
Sorry, I didn't scroll down enough, and found [the preview URL](https://federalist-e3fba26d-2806-4f02-bf0e-89c97cfba93c.app.cloud.gov/preview/atbcb/usab-uswds/philbratta-ICT-landing-page/ict.html).

It looks good!  But as I wrote above, the challenge is that we need trickier traffic direction than what we need to provide for ADA/ABA.

**Comment by philbratta** [comment]
Ok, I’ve drafted another version that includes the three links, which are pretty much verbatim from the current page. I think those sentences work as is. I also removed the link to the revised 255. 

If you still think the prose doesn’t explain 508 and 255 ideas and differentiation well, do let me know. I’m happy to take another stab at writing up the content with greater specificity and/or starker differences between 508 and 255.  

I’ve created another pull request (“philbratta -- ICT landing page with three necessary links”).

**Comment by bruce-usab** [comment]
Thanks Phil!  I pulled your changes into master.
