### ISSUE TITLE
TOC focus outline cut off

### ISSUE THREAD

**Issue by kengdoj** [atbcb/usab-uswds#907]
Tab through the left side toc. The focus outline is not displaying consistently (some have no top and bottom outline) on each item. Margins prob need adjustment.

**Comment by bruce-usab** [comment]
@kengdoj can you please add a screen clip?  I was not able to spot an example of this on the first place (ADAAG) I looked for it.  Thank you.

**Comment by kengdoj** [comment]
![snip of cutoff outline](https://user-images.githubusercontent.com/21043936/102151105-1a007a00-3e40-11eb-94dc-b245f5f0d0bd.png)
