### ISSUE TITLE
Netlify webinar date and time not working

### ISSUE THREAD

**Issue by RSD-accessboard** [atbcb/usab-uswds#95]
The time portion of the webinar date and time cannot switch to a.m. to p.m., and does not save. This may be Netlify issue

**Comment by RSD-accessboard** [comment]
When adding a news article, having issues with saving and publishing. Keeps saying it's not saved

**Comment by RSD-accessboard** [comment]
The tags were added directly to master, but the news said it was not saved but showed up as pull requests

**Comment by RSD-accessboard** [comment]
See Randall's latest branch, or master. Check that netlify admin settings for proper capture of date and time, and then check webinars/index for proper display of time

**Comment by apburnes** [comment]
Updated datetime format in the webinar time widget.  See PR #115 to close this issue.
