### ISSUE TITLE
How do we get an IP address (can be IPv6) for the site?

### ISSUE THREAD

**Issue by bruce-usab** [atbcb/usab-uswds#97]
Switchover (Bruce suggests 11:59pm 7/4) from Devis hosted site will require an IP address for DNS table updates.

Charles has what he needs to initiate that.  IP can be v6 if that makes things easier.

**Comment by apburnes** [comment]
The underlying AWS infrastructure Federalist leverages doesn't provide us with a static IP address.  To switch over DNS, Federalist uses CNAMES and [this checklist](https://federalist.18f.gov/documentation/launch-checklist/) has the steps for getting DNS changes setup.  For more in depth information on Federalist custom domains, here is our [documentation](https://federalist.18f.gov/documentation/custom-urls/).

**Comment by bruce-usab** [comment]
I forwarded to Charles Washington, our CTO/CSIO.
